env: dev

log:
  level: debug

api:
  http:
    port: 8081
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9091

cluster:
  id: test
  keylength: 16
  partitions: 16
  pepper: sriracha
  replicas: 3
  surrogates: 1
  node:
    id: 2
    raft_dir: /var/lib/shackle/raft2
    addr_raft: 127.0.0.1:4719
    addr_int_api: 127.0.0.1:4718
    vnode_count: 8
    meta:
      zone: b

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 10s
    path_ix: /data/node2
    path_ts: /data/node2
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9101
  log:
    enabled: true
    level: info
