env: dev

log:
  level: debug

api:
  http:
    port: 8082
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9092

cluster:
  id: test
  keylength: 16
  partitions: 16
  pepper: sriracha
  replicas: 3
  surrogates: 1
  node:
    id: 3
    raft_dir: /var/lib/shackle/raft3
    raft_port: 4729
    data_port: 4728

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 10s
    path_ix: /data/node3
    path_ts: /data/node3
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9102
  log:
    enabled: true
    level: info
