env: dev

log:
  level: debug

api:
  http:
    port: 8081
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9091

cluster:
  id: test
  partitions: 64
  raft:
    node_id: 1
    port: 4719
    join: 127.0.0.1:4709
  replicas: 3
  surrogates: 1

data:
  keylength: 16
  partitions: 64
  pepper: sriracha
  port: 4718

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 30s
    path_ix: /data/node2
    path_ts: /data/node2
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9101
  log:
    enabled: true
    level: info
