env: dev

log:
  level: debug

api:
  enabled: true
  http:
    port: 8082
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9092

cluster:
  enabled: true
  id: test
  partitions: 64
  replicas: 3
  surrogates: 1
  raft:
    node_id: 3
    port: 4729
    join: 127.0.0.1:4709

data:
  keylength: 16
  partitions: 4096
  pepper: sriracha
  port: 4728

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 30s
    path_ix: /data/node3
    path_ts: /data/node3
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9102
  log:
    enabled: true
    level: info
