env: dev

log:
  level: debug

api:
  enabled: true
  http:
    port: 8080
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9090

cluster:
  enabled: true
  id: test
  partitions: 64
  raft:
    node_id: 1
    port: 4709
  replicas: 3
  surrogates: 1

data:
  port: 4708
  pepper: sriracha
  keylength: 16

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 30s
    path_ix: /data/node1
    path_ts: /data/node1
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9100
  log:
    enabled: true
    level: info
