env: dev

log:
  level: debug

api:
  enabled: true
  http:
    port: 8081
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9091

raft:
  clusterid: test
  nodeid: 2
  port: 4719
  join: 127.0.0.1:4709

data:
  port: 4718
  pepper: pepper
  shards: 4096
  vnodes: 4
  replicas: 3
  surrogates: 1
