env: dev

log:
  level: debug

api:
  http:
    port: 8080
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9090

cluster:
  id: test
  keylength: 16
  partitions: 16
  pepper: sriracha
  replicas: 3
  surrogates: 1
  node:
    id: 1
    raft_dir: /var/lib/shackle/raft1
    raft_solo: true
    raft_port: 4709
    data_port: 4708
    join:
      - id: 2
        addr: 127.0.0.1:4719
      - id: 3
        addr: 127.0.0.1:4729

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 10s
    path_ix: /data/node1
    path_ts: /data/node1
    sweep_interval: 1s

monitor:
  prometheus:
    port: 9100
  log:
    enabled: true
    level: info
