// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/event/event.proto

package event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Tick events are emitted by the deployment leader at regular intervals.
// This maintains a monotonic clock for all clusters in the deployment.
// These events are intended to be propagated to all clusters in the deployment.
type Tick struct {
	Epoch                uint32   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tick) Reset()         { *m = Tick{} }
func (m *Tick) String() string { return proto.CompactTextString(m) }
func (*Tick) ProtoMessage()    {}
func (*Tick) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f427997a424e26c, []int{0}
}

func (m *Tick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tick.Unmarshal(m, b)
}
func (m *Tick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tick.Marshal(b, m, deterministic)
}
func (m *Tick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tick.Merge(m, src)
}
func (m *Tick) XXX_Size() int {
	return xxx_messageInfo_Tick.Size(m)
}
func (m *Tick) XXX_DiscardUnknown() {
	xxx_messageInfo_Tick.DiscardUnknown(m)
}

var xxx_messageInfo_Tick proto.InternalMessageInfo

func (m *Tick) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// HostMetaUpdate events are proposed by hosts upon joining a deployment.
// They are design to update the node's information in the manifest if it requires updating.
type HostMetaUpdate struct {
	Id                   uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IntApiAddr           string            `protobuf:"bytes,2,opt,name=intApiAddr,proto3" json:"intApiAddr,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Databases            []string          `protobuf:"bytes,4,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HostMetaUpdate) Reset()         { *m = HostMetaUpdate{} }
func (m *HostMetaUpdate) String() string { return proto.CompactTextString(m) }
func (*HostMetaUpdate) ProtoMessage()    {}
func (*HostMetaUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f427997a424e26c, []int{1}
}

func (m *HostMetaUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostMetaUpdate.Unmarshal(m, b)
}
func (m *HostMetaUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostMetaUpdate.Marshal(b, m, deterministic)
}
func (m *HostMetaUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostMetaUpdate.Merge(m, src)
}
func (m *HostMetaUpdate) XXX_Size() int {
	return xxx_messageInfo_HostMetaUpdate.Size(m)
}
func (m *HostMetaUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_HostMetaUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_HostMetaUpdate proto.InternalMessageInfo

func (m *HostMetaUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HostMetaUpdate) GetIntApiAddr() string {
	if m != nil {
		return m.IntApiAddr
	}
	return ""
}

func (m *HostMetaUpdate) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *HostMetaUpdate) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

// HostStatusUpdate events are proposed by hosts to change their status.
// They may also be proposed by the deployment leader if a node is determined to be down.
type HostStatusUpdate struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostStatusUpdate) Reset()         { *m = HostStatusUpdate{} }
func (m *HostStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*HostStatusUpdate) ProtoMessage()    {}
func (*HostStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f427997a424e26c, []int{2}
}

func (m *HostStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostStatusUpdate.Unmarshal(m, b)
}
func (m *HostStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostStatusUpdate.Marshal(b, m, deterministic)
}
func (m *HostStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostStatusUpdate.Merge(m, src)
}
func (m *HostStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_HostStatusUpdate.Size(m)
}
func (m *HostStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_HostStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_HostStatusUpdate proto.InternalMessageInfo

func (m *HostStatusUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HostStatusUpdate) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// DeploymentStatusUpdate events are proposed by deployment leaders to change the status of the deployment.
type DeploymentStatusUpdate struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentStatusUpdate) Reset()         { *m = DeploymentStatusUpdate{} }
func (m *DeploymentStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatusUpdate) ProtoMessage()    {}
func (*DeploymentStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f427997a424e26c, []int{3}
}

func (m *DeploymentStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatusUpdate.Unmarshal(m, b)
}
func (m *DeploymentStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatusUpdate.Marshal(b, m, deterministic)
}
func (m *DeploymentStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatusUpdate.Merge(m, src)
}
func (m *DeploymentStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatusUpdate.Size(m)
}
func (m *DeploymentStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatusUpdate proto.InternalMessageInfo

func (m *DeploymentStatusUpdate) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Tick)(nil), "event.Tick")
	proto.RegisterType((*HostMetaUpdate)(nil), "event.HostMetaUpdate")
	proto.RegisterMapType((map[string]string)(nil), "event.HostMetaUpdate.MetaEntry")
	proto.RegisterType((*HostStatusUpdate)(nil), "event.HostStatusUpdate")
	proto.RegisterType((*DeploymentStatusUpdate)(nil), "event.DeploymentStatusUpdate")
}

func init() {
	proto.RegisterFile("entity/event/event.proto", fileDescriptor_4f427997a424e26c)
}

var fileDescriptor_4f427997a424e26c = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x24, 0x2d, 0x64, 0xa4, 0xa5, 0x2c, 0x52, 0x82, 0x14, 0x0d, 0xc1, 0x43, 0x4e,
	0xa9, 0xd8, 0x83, 0xd2, 0x5b, 0x45, 0xc1, 0x8b, 0x97, 0x55, 0x2f, 0xde, 0xb6, 0xdd, 0xc1, 0x2c,
	0x4d, 0xb3, 0xa1, 0x3b, 0x0d, 0xe4, 0x1d, 0x7d, 0x28, 0xc9, 0xa6, 0xd8, 0xf4, 0xe0, 0x65, 0x99,
	0x7f, 0x76, 0xbe, 0x99, 0x7f, 0x18, 0x88, 0xb0, 0x24, 0x4d, 0xcd, 0x1c, 0x6b, 0x2c, 0xa9, 0x7b,
	0xb3, 0x6a, 0x6f, 0xc8, 0xf0, 0x81, 0x13, 0xc9, 0x0c, 0x82, 0x0f, 0xbd, 0xd9, 0xf2, 0x4b, 0x18,
	0x60, 0x65, 0x36, 0x79, 0xc4, 0x62, 0x96, 0x8e, 0x44, 0x27, 0x92, 0x1f, 0x06, 0xe3, 0x57, 0x63,
	0xe9, 0x0d, 0x49, 0x7e, 0x56, 0x4a, 0x12, 0xf2, 0x31, 0x78, 0x5a, 0xb9, 0xaa, 0x40, 0x78, 0x5a,
	0xf1, 0x6b, 0x00, 0x5d, 0xd2, 0xaa, 0xd2, 0x2b, 0xa5, 0xf6, 0x91, 0x17, 0xb3, 0x34, 0x14, 0xbd,
	0x0c, 0x5f, 0x40, 0xb0, 0x43, 0x92, 0x91, 0x1f, 0xfb, 0xe9, 0xc5, 0xfd, 0x4d, 0xd6, 0x79, 0x38,
	0x6f, 0x9a, 0xb5, 0xe1, 0x4b, 0x49, 0xfb, 0x46, 0xb8, 0x62, 0x3e, 0x83, 0x50, 0x49, 0x92, 0x6b,
	0x69, 0xd1, 0x46, 0x41, 0xec, 0xa7, 0xa1, 0x38, 0x25, 0xae, 0x1e, 0x20, 0xfc, 0x03, 0xf8, 0x04,
	0xfc, 0x2d, 0x36, 0xce, 0x50, 0x28, 0xda, 0xb0, 0x5d, 0xa5, 0x96, 0xc5, 0x01, 0x8f, 0x66, 0x3a,
	0xb1, 0xf4, 0x1e, 0x59, 0xb2, 0x84, 0x49, 0x3b, 0xf8, 0x9d, 0x24, 0x1d, 0xec, 0x3f, 0xfb, 0x4c,
	0x61, 0x68, 0xdd, 0xbf, 0xc3, 0x47, 0xe2, 0xa8, 0x92, 0x3b, 0x98, 0x3e, 0x63, 0x55, 0x98, 0x66,
	0x87, 0xe5, 0x79, 0x87, 0x13, 0xc1, 0xfa, 0xc4, 0xd3, 0xed, 0x57, 0x92, 0xeb, 0xef, 0xbc, 0x36,
	0xc5, 0x61, 0x87, 0x99, 0x36, 0x73, 0x9b, 0xcb, 0xcd, 0xb6, 0xc0, 0x79, 0xff, 0x26, 0xeb, 0xa1,
	0x3b, 0xc7, 0xe2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x20, 0x23, 0xc0, 0xaa, 0x01, 0x00, 0x00,
}
