env: dev

log:
  level: debug

api:
  http:
    port: 8082
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9092

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 10s
    path: /data/node3
    sweep_interval: 10s

monitor:
  prometheus:
    port: 9102
  log:
    enabled: true
    level: info

node_host:
  id: 3
  deployment_id: 1
  keylength: 16
  partitions: 64
  pepper: sriracha
  replica_count: 2
  witness_count: 1
  int_api_addr: 127.0.0.1:4728
  raft_addr: 127.0.0.1:4729
  raft_dir: /data/raft3
  raft_solo: true
  meta:
    zone: c
  vary:
    - zone
