env: dev

log:
  level: debug

api:
  http:
    port: 8081
    keepalive: true
    keepalive_period: 60s
    max_conns_per_ip: 10000
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 15s
  grpc:
    port: 9091

repo:
  hash:
    cachesize: 100000
    expiration_batch_size: 1000
    key_expiration: 730h
    lock_expiration: 10s
    sweep_interval: 10s
    path_ix: /data-nvme/node2
    disks:
      - path: /data-nvme/node2
        capacity: 8

monitor:
  prometheus:
    port: 9101
  log:
    enabled: true
    level: info

host:
  id: 2
  deployment_id: 1
  keylength: 16
  partitions: 16
  pepper: sriracha
  replica_count: 2
  witness_count: 1
  int_api_addr: 127.0.0.1:4718
  raft_addr: 127.0.0.1:4719
  raft_dir: /data/raft2
  meta:
    zone: b
  vary:
    - zone
