// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpcint/grpc.proto

package grpcint

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Batch operation
type BatchOp struct {
	Op                   uint32   `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Items                []byte   `protobuf:"bytes,2,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchOp) Reset()         { *m = BatchOp{} }
func (m *BatchOp) String() string { return proto.CompactTextString(m) }
func (*BatchOp) ProtoMessage()    {}
func (*BatchOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed77ff4c20ddf65, []int{0}
}

func (m *BatchOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchOp.Unmarshal(m, b)
}
func (m *BatchOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchOp.Marshal(b, m, deterministic)
}
func (m *BatchOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchOp.Merge(m, src)
}
func (m *BatchOp) XXX_Size() int {
	return xxx_messageInfo_BatchOp.Size(m)
}
func (m *BatchOp) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchOp.DiscardUnknown(m)
}

var xxx_messageInfo_BatchOp proto.InternalMessageInfo

func (m *BatchOp) GetOp() uint32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *BatchOp) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

// Batch Reply
type BatchReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Res                  []byte   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchReply) Reset()         { *m = BatchReply{} }
func (m *BatchReply) String() string { return proto.CompactTextString(m) }
func (*BatchReply) ProtoMessage()    {}
func (*BatchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed77ff4c20ddf65, []int{1}
}

func (m *BatchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchReply.Unmarshal(m, b)
}
func (m *BatchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchReply.Marshal(b, m, deterministic)
}
func (m *BatchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchReply.Merge(m, src)
}
func (m *BatchReply) XXX_Size() int {
	return xxx_messageInfo_BatchReply.Size(m)
}
func (m *BatchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchReply.DiscardUnknown(m)
}

var xxx_messageInfo_BatchReply proto.InternalMessageInfo

func (m *BatchReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *BatchReply) GetRes() []byte {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*BatchOp)(nil), "grpcint.BatchOp")
	proto.RegisterType((*BatchReply)(nil), "grpcint.BatchReply")
}

func init() {
	proto.RegisterFile("api/grpcint/grpc.proto", fileDescriptor_4ed77ff4c20ddf65)
}

var fileDescriptor_4ed77ff4c20ddf65 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2f, 0x2a, 0x48, 0xce, 0xcc, 0x2b, 0x01, 0xd3, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xec, 0x50, 0x31, 0x25, 0x7d, 0x2e, 0x76, 0xa7, 0xc4, 0x92, 0xe4, 0x0c, 0xff, 0x02, 0x21, 0x3e,
	0x2e, 0xa6, 0xfc, 0x02, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0xa6, 0xfc, 0x02, 0x21, 0x11,
	0x2e, 0xd6, 0xcc, 0x92, 0xd4, 0xdc, 0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47,
	0xc9, 0x80, 0x8b, 0x0b, 0xac, 0x21, 0x28, 0xb5, 0x20, 0xa7, 0x52, 0x48, 0x80, 0x8b, 0x39, 0xb5,
	0xa8, 0x08, 0xac, 0x89, 0x33, 0x08, 0xc4, 0x04, 0x89, 0x14, 0xa5, 0xc2, 0xf4, 0x80, 0x98, 0x46,
	0x8e, 0x5c, 0x5c, 0x2e, 0xa9, 0x39, 0xa9, 0xe9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x42, 0xc6, 0x5c,
	0x1c, 0x50, 0x5e, 0xaa, 0x90, 0x80, 0x1e, 0xd4, 0x19, 0x7a, 0x50, 0x37, 0x48, 0x09, 0xa3, 0x8a,
	0x80, 0x2d, 0x51, 0x62, 0x70, 0x52, 0x8e, 0x52, 0xcc, 0xc8, 0x4c, 0xcf, 0x28, 0xcb, 0xcf, 0x29,
	0xcd, 0x4d, 0xd5, 0xcb, 0xcc, 0xd7, 0x2f, 0xce, 0x48, 0x4c, 0xce, 0xce, 0x49, 0xd5, 0x47, 0xf2,
	0x5e, 0x12, 0x1b, 0xd8, 0x6b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xa9, 0x17, 0xa5,
	0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DelegationClient is the client API for Delegation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DelegationClient interface {
	// Delegate executes a batch operation delegated by another node
	Delegate(ctx context.Context, in *BatchOp, opts ...grpc.CallOption) (*BatchReply, error)
}

type delegationClient struct {
	cc grpc.ClientConnInterface
}

func NewDelegationClient(cc grpc.ClientConnInterface) DelegationClient {
	return &delegationClient{cc}
}

func (c *delegationClient) Delegate(ctx context.Context, in *BatchOp, opts ...grpc.CallOption) (*BatchReply, error) {
	out := new(BatchReply)
	err := c.cc.Invoke(ctx, "/grpcint.Delegation/Delegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelegationServer is the server API for Delegation service.
type DelegationServer interface {
	// Delegate executes a batch operation delegated by another node
	Delegate(context.Context, *BatchOp) (*BatchReply, error)
}

// UnimplementedDelegationServer can be embedded to have forward compatible implementations.
type UnimplementedDelegationServer struct {
}

func (*UnimplementedDelegationServer) Delegate(ctx context.Context, req *BatchOp) (*BatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delegate not implemented")
}

func RegisterDelegationServer(s *grpc.Server, srv DelegationServer) {
	s.RegisterService(&_Delegation_serviceDesc, srv)
}

func _Delegation_Delegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchOp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegationServer).Delegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcint.Delegation/Delegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegationServer).Delegate(ctx, req.(*BatchOp))
	}
	return interceptor(ctx, in, info, handler)
}

var _Delegation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcint.Delegation",
	HandlerType: (*DelegationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delegate",
			Handler:    _Delegation_Delegate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpcint/grpc.proto",
}
